import ProjectDescription
import ProjectDescriptionHelpers
import SkeletonPlugin

let workspace = Workspace(name: Constants.projectName,
                        projects: [.relativeToRoot("Sources/**")],
                         generationOptions: .options(enableAutomaticXcodeSchemes: false,
                                                     autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .all,
                                                                                             testingOptions: .parallelizable,
                                                                                             testLanguage: nil,
                                                                                             testRegion: nil,
                                                                                             testScreenCaptureFormat: nil),
                                                     lastXcodeUpgradeCheck: .init(26, 0, 0),
                                                     renderMarkdownReadme: true))   
