name: Project
description: A group of procedures to handle a Skeleton project
procedures:
- name: core
  description: An empty core module
  items:
  - core/config.yml
- name: deviceCapability
  description: An empty device capability module
  items:
  - deviceCapability/config.yml
- name: feature
  description: An empty featureModule framework
  items:
  - feature/config.yml
- name: useCase
  description: A use case for a scene with unit tests
  items:
  - useCase/config.yml


