name: deviceCapability
parameters: 
- name: name
  isRequired: true
  description: "Name of the Device Capability module."
- name: tuist.config.deviceCapability
  isRequired: true
- name: fileHeader
  isRequired: true
paths: 
- from: Module
  to: Sources/DeviceCapabilities/{{name|firstUppercase}}
description: A core module.
plugins:
  shell:
    after:  
    - "cd Sources/DeviceCapabilities/{{name|firstUppercase}}/ && mise exec -- sourcery --config sourcery.yml"
replacements: 
  - text: |
          static func {{name|firstLowercase}}() -> Self {
              .init(name: "{{name|firstUppercase}}",
              destinations: Constants.destinations,
              deploymentTargets: .custom,
              swiftVersion: .v6,
              dependencies: .init(utilities: [.dataStructures(), .logger(), .dependencyContainer(), .streams()],
                                  external: []),
              testDependencies: .init(test: [.coreTesting()],
                                      external: []),
              synthesizers: [],
              hasMacros: false)
          }
    destination: "{{tuist.config.deviceCapability}}"
    placeholder: "// murray: declaration"

  - text: |
          .{{name|firstLowercase}}(),
    destination: "{{tuist.workspace.config}}"
    placeholder: "// murray: device capability integration"
    
    