extension String: Equatable {}
extension Bool: Equatable {}
extension URL: Equatable {}
extension Int: Equatable {}
extension Int64: Equatable {}
extension Double: Equatable {}
extension CGFloat: Equatable {}
extension Float: Equatable {}
extension UIImage: Equatable {}
extension CGSize: Equatable {}
extension CGRect: Equatable {}
extension CGPoint: Equatable {}
