name: useCase
parameters: 
- name: name
  isRequired: true
- name: feature
  isRequired: true
paths: 
- from: UseCase.swift.stencil
  to: "{{features.sources}}/UseCases/{{name|firstUppercase}}UseCase.swift"
- from: UseCaseTests.swift.stencil
  to: "{{features.tests}}/UseCases/{{name|firstUppercase}}UseCaseTests.swift"
description: A usecase with tests
replacements: 
- text: |
          register(for: {{name|firstUppercase}}UseCase.self, scope: .singleton) {
            {{name|firstUppercase}}UseCaseImplementation()
          }
  destination: "{{features.sources}}/Feature+UseCases.swift"
  placeholder: "// murray: registration"
