name: core
parameters: 
- name: name
  isRequired: true
  description: "Name of the Core module."
- name: tuist.config.core
  isRequired: true
- name: fileHeader
  isRequired: true
paths: 
- from: Module
  to: Sources/Core/{{name|firstUppercase}}
description: A core module.
plugins:
  shell:
    after:  
    - "pwd && cd Sources/Core/{{name|firstUppercase}}/ && mise exec -- sourcery --config sourcery.yml"
replacements: 
  - text: |
          static func {{name|firstLowercase}}() -> Skeleton.CoreModule {
              .init(name: "{{name|firstUppercase}}",
              destinations: Constants.destinations,
              deploymentTargets: .custom,
              swiftVersion: .v6,
              dependencies: .init(block: [.dataStructures(), .logger(), .dependencyContainer(), .streams()],
                                  core: []),
              testDependencies: .init(test: [.coreTesting()],
                                      external: []),
              synthesizers: [],
              hasMacros: false)
          }
    destination: "{{tuist.config.core}}"
    placeholder: "// murray: declaration"

  - text: |
          .{{name|firstLowercase}}(),
    destination: "{{tuist.workspace.config}}"
    placeholder: "// murray: core integration"
    
    